### PR TITLE
Add url for water system locations

### PR DESCRIPTION
**Pull request by r-b-g-b**
Note to self, here's code for converting to geojson:

```python
# from https://stackoverflow.com/questions/43119040/shapefile-into-geojson-conversion-python-3
import shapefile
from json import dumps

# read the shapefile
reader = shapefile.Reader("my.shp")
fields = reader.fields[1:]
field_names = [field[0] for field in fields]
buffer = []
for sr in reader.shapeRecords():
   atr = dict(zip(field_names, sr.record))
   geom = sr.shape.__geo_interface__
   buffer.append(dict(type="Feature", \
    geometry=geom, properties=atr)) 

# write the GeoJSON file
geojson = open("pyshp-demo.json", "w")
geojson.write(dumps({"type": "FeatureCollection", "features": buffer}, indent=2) + "\n")
geojson.close()
```

### CODE REVIEW

**Comment by r-b-g-b** [comment]
@skyballin Mind pulling this branch and seeing if you can run

```bash
pip install -r requirements.txt
make data
```

Thanks!

**Review by skyballin — COMMENTED** [review]
From within the clean_water_tool environment, 'make data' error'ed out here:

>notebook>=4.3.1->jupyterlab->-r requirements.txt (line 10)) (0.1.7)
Installing collected packages: entrypoints, pycodestyle, pyflakes, flake8, python-dotenv, src
  Found existing installation: entrypoints 0.2.3
Cannot uninstall 'entrypoints'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
make: *** [requirements] Error 1

**Comment by skyballin** [comment]
https://github.com/blockstack/blockstack-core/issues/504

Looks like a fix above

**Comment by r-b-g-b** [comment]
Are you/can you try running this from a brand new virtualenv?

**Comment by skyballin** [comment]
Removed environment, tried to make create_environment and ran into this error:

RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.

**Comment by r-b-g-b** [comment]
Huh... `conda update conda`?

**Comment by skyballin** [comment]
Downgraded from Anaconda3 to Anaconda2 

Ran make create_environment 
All worked when doing this.

Activated clean_water_tool
Ran make data
All worked when doing this. 

Pull request approved!

**Pull request merged**
